// achievementsData.js
export const achievementsData = [
    {
      id: '1',
      title: 'First Bingo!',
      description: 'Completed your first Bingo card!',
      rarity: 'Common',
      xp: '100',
      color: '#FF5733',
    },
    {
      id: '2',
      title: 'Double Bingo',
      description: 'Achieved two Bingos in a single game.',
      rarity: 'Uncommon',
      xp: '250',
      color: '#3498DB',
    },
    {
      id: '3',
      title: 'Line Master',
      description: 'Completed all horizontal lines.',
      rarity: 'Uncommon',
      xp: '300',
       color: '#00FF7F',
    },
    {
      id: '4',
      title: 'Column Conqueror',
      description: 'Completed all vertical columns.',
      rarity: 'Uncommon',
      xp: '300',
       color: '#A020F0',
    },
    {
      id: '5',
      title: 'Full House',
      description: 'Filled the entire Bingo card.',
      rarity: 'Rare',
      xp: '500',
        color: '#FFFF00',
    },
    {
      id: '6',
      title: 'Speed Bingo',
      description: 'Achieved Bingo in under 10 calls.',
      rarity: 'Rare',
      xp: '750',
       color: '#FF0000',
    },
    {
      id: '7',
      title: 'Lucky Streak',
      description: 'Won three Bingo games in a row.',
      rarity: 'Epic',
      xp: '1000',
        color: '#00FFFF',
    },
    {
      id: '8',
      title: 'Number Hunter',
      description: 'Called every number on the card.',
      rarity: 'Epic',
      xp: '1000',
        color: '#1E90FF',
    },
    {
      id: '9',
      title: 'Bingo Pro',
      description: 'Won 50 bingo games.',
      rarity: 'Legendary',
      xp: '1500',
      color: '#C0C0C0',
    },
    {
      id: '10',
      title: 'Bingo Master',
      description: 'Won 100 bingo games.',
      rarity: 'Legendary',
      xp: '2000',
        color: '#FF5733',
    },
    {
      id: '11',
      title: 'Diagonal Dynamo',
      description: 'Complete both the diagonal lines on a card.',
      rarity: 'Rare',
      xp: '600',
      color: '#3498DB',
    },
    {
      id: '12',
      title: 'The Collector',
      description: 'Collect all unique numbers on your Bingo cards',
      rarity: 'Epic',
      xp: '1250',
      color: '#00FF7F',
    },
    {
      id: '13',
      title: 'Early Bird Bingo',
      description: 'Get a bingo on the first 5 calls ',
      rarity: 'Epic',
      xp: '1250',
       color: '#A020F0',
    },
    {
      id: '14',
      title: 'Card Magician',
      description: 'Complete a full house with a 9 number calls.',
      rarity: 'Legendary',
      xp: '2250',
         color: '#FFFF00',
    },
    {
      id: '15',
      title: 'Bingo God',
      description: 'Won 200 bingo games.',
      rarity: 'Legendary',
      xp: '3000',
        color: '#FF0000',
        owned: true
    }
  ];